name: CI/CD workflow 1

env:
  SERVER_IP: "64.225.82.49"
  SERVER_USER: root
on:
  push:
    branches: main

jobs:
  check-tests-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: checkout le code
        uses: actions/checkout@v4
      - name: installer node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: ./server/package-lock.json

      - name: install dependencies
        run: npm ci --prefer-offline

      - name: vérifie le code
        run: npm run lint

      - name: vérifie les vulnérabilités des dépendances
        run: npm audit || true

      - name: exécute les test
        run: npm run test:ci

      - name: Upload du rapport de couverture sur Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  check-tests-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: checkout le code
        uses: actions/checkout@v4

      - name: installer node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json

      - name: install dependencies
        run: npm ci --prefer-offline

      - name: vérifie le code
        run: npm run lint
      - name: vérifie les vulnérabilités des dépendances

        run: npm audit || true

  build-frontend:
    needs: check-tests-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: checkout le code
        uses: actions/checkout@v4

      - name: installer node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json

      - name: install dependencies
        run: npm ci --prefer-offline

      - name: build frontend
        run: npm run build

      - name: upload build artefcat
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./client/dist

  build-e2e-frontend:
    needs: check-tests-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: checkout le code
        uses: actions/checkout@v4

      - name: installer node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json

      - name: install dependencies
        run: npm ci --prefer-offline

      - name: build frontend
        run: npm run build

      - name: upload build artefcat
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist-e2e
          path: ./client/dist

  test-e2e-frontend:
    needs: build-e2e-frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ["chrome", "edge", "firefox"]
    steps:
      - name: checkout le code
        uses: actions/checkout@v4

      - name: installer node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"

      - name: artifact frontend for e2e build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist-e2e
          path: ./client/dist

      - name: install server dependencies
        run: |
          cd server 
          npm ci --prefer-offline

      - name: start backend
        run: |
          cd server
          npm start &

      - name: cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./client
          browser: ${{ matrix.browser }}
          start: npm run preview
          wait-on: http://localhost:4173
          wait-on-timeout: 60
          config: baseUrl=http://localhost:4173

      - name: Upload du rapport de couverture sur Codecov
        if: matrix.browser == 'chrome' # pour ne pas uploader 3 fois le rapport
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: [check-tests-backend, test-e2e-frontend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: download build artefact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./dist
      - name: déployer le server
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_KEY_VPS }}"
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          scp -r ./server ${SERVER_USER}@${SERVER_IP}:/var/www
          scp -r ./dist ${SERVER_USER}@${SERVER_IP}:/var/www
          ssh $SERVER_USER@$SERVER_IP "cd /var/www/server && npm install --omit=dev"
          ssh $SERVER_USER@$SERVER_IP "cd /var/www/server && pm2 startOrRestart ecosystem.config.js --env production && pm2 save"
